# Generated by Django 5.0 on 2024-01-05 08:16

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='red_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdef1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
