# Generated by Django 5.0 on 2024-01-06 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_red_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='red_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
