# Generated by Django 5.0 on 2024-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_kyc_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='kyc'),
        ),
    ]
