# Generated by Django 5.0 on 2024-01-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
